// Image-based replacement for the <ColorDot> custom-View map markers.
//
// react-native-maps' custom-View markers (a plain JSX child passed to
// <Marker>) have a long-standing, unfixed Android bug: `anchor` isn't
// reliably honored, because Android snapshots the JS-rendered child into a
// bitmap and the anchor offset can be computed against the wrong measured
// size (react-native-maps/react-native-maps GitHub issues #230, #328,
// #5435 — the last closed by the maintainers as "not planned", i.e. no
// upstream fix is coming). Confirmed on a real device in this project: a
// river gauge's coordinate reverse-geocoded to the exact correct street,
// yet the marker rendered visibly out in the ocean.
//
// Image-based markers don't have this ambiguity — Android gets a real
// bitmap with known pixel dimensions immediately, instead of snapshotting a
// View whose layout may not have settled yet. These PNGs are generated by
// scripts/generate-marker-dots.js (re-run it if a marker color ever
// changes) and `require()`'d statically here so Metro bundles them once.
// react-native-maps' Marker.image prop is typed as `number | ImageURISource`
// (its own narrower type), not React Native's general ImageSourcePropType
// (which can also be an array, for multi-resolution image sets) — a single
// require() of one PNG always resolves to a plain numeric asset id, so
// `number` is both the correct and the simplest type here.
type DotColorName = "green" | "blue" | "gray" | "lightgray" | "red" | "amber" | "orange" | "pink";

// Every distinct hex color used by a map marker across both map files.
const HEX_TO_NAME: Record<string, DotColorName> = {
  "#16a34a": "green",
  "#2563eb": "blue",
  "#6b7280": "gray",
  "#9ca3af": "lightgray",
  "#dc2626": "red",
  "#f59e0b": "amber",
  "#f97316": "orange",
  "#f9a8d4": "pink",
};

const IMAGES: Record<DotColorName, { small: number; large: number }> = {
  green: { small: require("../../assets/dots/green-small.png"), large: require("../../assets/dots/green-large.png") },
  blue: { small: require("../../assets/dots/blue-small.png"), large: require("../../assets/dots/blue-large.png") },
  gray: { small: require("../../assets/dots/gray-small.png"), large: require("../../assets/dots/gray-large.png") },
  lightgray: {
    small: require("../../assets/dots/lightgray-small.png"),
    large: require("../../assets/dots/lightgray-large.png"),
  },
  red: { small: require("../../assets/dots/red-small.png"), large: require("../../assets/dots/red-large.png") },
  amber: { small: require("../../assets/dots/amber-small.png"), large: require("../../assets/dots/amber-large.png") },
  orange: {
    small: require("../../assets/dots/orange-small.png"),
    large: require("../../assets/dots/orange-large.png"),
  },
  pink: { small: require("../../assets/dots/pink-small.png"), large: require("../../assets/dots/pink-large.png") },
};

// `size` mirrors the dp value the old <ColorDot size={n}/> used to take.
// Everything below 24 (every fixed marker size in both files — 10-18) maps
// to the "small" image; only the areas tab's count-scaled dot (up to 36)
// crosses into "large". This trades the old continuous per-count scaling
// for two discrete tiers — a deliberate, small scope cut to make the fix
// tractable, not an oversight (see CLAUDE.md).
//
// FIXED (user-reported crash: "Cannot read property 'toLowerCase' of
// undefined"): every call site in AreaSeverityMap.tsx/SituationMapScreen.tsx
// passes the result of a `Record<string,string>` lookup (e.g.
// LEVEL_COLOR[a.level]) straight through with no fallback — TypeScript
// types that as `string`, not `string | undefined`, since this project
// doesn't enable `noUncheckedIndexedAccess`, so a genuinely missing key
// (a status value the map doesn't know about yet, a partial/malformed API
// response, a race on first render) compiles clean but crashes at runtime.
// Every server-side enum feeding these lookups was checked and is fully
// covered today, but the failure mode — one unmapped value anywhere taking
// the whole map screen down — is exactly the kind of thing this project's
// "fail soft" convention exists to prevent (see e.g. GDACS_ALERT_COLOR's
// own `|| "#6b7280"` fallback, already used at one call site but not
// enforced everywhere). Hardened centrally here instead of patching each
// of the 14 call sites individually, so every current and future caller is
// covered by construction, not by remembering to add `|| "#fallback"`.
export function dotImage(hexColor: string | undefined | null, size = 16): number {
  const name = hexColor ? (HEX_TO_NAME[hexColor.toLowerCase()] ?? "gray") : "gray";
  return IMAGES[name][size >= 24 ? "large" : "small"];
}
